FROM ubuntu:18.04

LABEL maintainer='Arvind Awasthi'

LABEL maintainer_id='awasthiarvind1997@gmail.com'

LABEL description='Installation and configuration of git and git-hub'

RUN apt-get update

RUN apt-get install git -y

CMD /bin/bash

